services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000

    environment:
      PGUSER: admin
      PGPASS: pass
      PORT: 5432
      PGDB: postgres
      HOST: db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
